config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/signup_choice', to: 'home#signup'

  devise_for :managers
  devise_for :residents, controllers: {
    passwords: 'residents/passwords'
  }

  resources :managers, only: [:new, :create] do
    get 'edit_photo', on: :member
    patch 'update_photo', on: :member
  end

  resources :residents, only: [:new, :create, :show, :update] do
    resources :visitors, only: [:new, :create, :index]
    resources :tenants, only: [:new, :create], on: :collection
    resources :owners, only: [:new, :create, :destroy], on: :collection
    get 'find_towers', on: :collection
    get 'confirm', on: :member
    get 'edit_photo', on: :member
    patch 'update_photo', on: :member
  end

  resources :visitors do
    post 'confirm_entry', on: :member
  end

  resource :units do
    get 'find_units', on: :collection
  end

  resources :common_areas, only: [:show, :edit, :update] do
    resources :reservations, only: [:create, :update] do
      post 'canceled', on: :member
    end
  end

  resources :unit_types, only: [:show, :edit, :update]
  resources :announcements, only: [:show, :edit, :update, :destroy]

  resources :bills, only: [:index, :show] do
    resources :receipts, only: [:new, :create]
  end

  resources :condos, only: [:new, :create, :show, :edit, :update] do
    get 'residents', on: :member
    resources :common_areas, only: [:new, :create]
    resources :unit_types, only: [:new, :create]
    resources :visitor_entries, only: [:index, :new, :create]
    resources :superintendents, only: [:show, :new, :create, :destroy]
    resources :announcements, only: [:index, :new, :create]

    resources :visitors do
      get 'find', on: :collection
      get 'all', on: :collection
    end
    resources :fines, only: [:new, :create]

    resources :towers, only: [:new, :create] do
      member do
        get :edit_floor_units
        patch :update_floor_units
      end
    end

    member do
      get 'add_manager'
      post 'associate_manager'
    end
  end

  resources :towers, only: [:show] do
    resources :floors, only: [:show] do
      resources :units, only: [:show]
    end
  end

  namespace :api do
    namespace :v1 do
      get 'check_owner', to: 'residents#check_owner'
      get 'get_tenant_residence', to: 'residents#tenant_residence'
      get 'get_owner_properties', to: 'residents#owner_properties'
      resources :common_areas, only: [:show]
      resources :units, only: [:show]
      resources :condos, only: [:index, :show] do
        resources :unit_types, only: [:index]
        resources :common_areas, only: [:index]
        resources :units, only: [:index]
      end
    end
  end

  direct :rails_blob do |blob, options|
    route_for(:rails_service_blob, blob.signed_id, blob.filename, options)
  end

  direct :rails_blob_variant do |variant, options|
    route_for(:rails_service_blob_variant, variant.blob.signed_id,
              variant.variation.key, variant.blob.filename, options)
  end

  direct :rails_blob_preview do |preview, options|
    route_for(:rails_service_blob_preview, preview.blob.signed_id,
              preview.variation.key, preview.blob.filename, options)
  end

  direct :rails_representation do |representation, options|
    if representation.blob.previewable?
      route_for(:rails_service_blob_preview, representation.blob.signed_id,
                representation.variation.key, representation.blob.filename, options)
    else
      route_for(:rails_service_blob_variant, representation.blob.signed_id,
                representation.variation.key, representation.blob.filename, options)
    end
  end
end

app/models/common_area.rb
class CommonArea < ApplicationRecord
  include CurrencyHelper

  belongs_to :condo
  has_many :reservations, dependent: :destroy

  validates :name, :description, :max_occupancy, presence: true
  validates :max_occupancy, numericality: { greater_than: 0 }

  def access_allowed?(resident)
    condo.residents.include?(resident)
  end

  def formatted_fee
    return fee if fee == 'Não encontrada'

    integer_to_brl(fee) || 'Não informada'
  end

  def fee
    url = "#{Rails.configuration.api['base_url']}/condos/#{condo.id}/common_area_fees"
    response = Faraday.get(url)

    common_area_fees = JSON.parse(response.body)
    this_fee = common_area_fees.find { |fee| fee['common_area_id'] == id }
    this_fee ? this_fee['value_cents'] : nil
  rescue Faraday::ConnectionFailed
    'Não encontrada'
  end
end

app/controllers/api/v1/common_areas_controller.rb
module Api
  module V1
    class CommonAreasController < Api::V1::ApiController
      before_action :set_condo, only: [:index]
      before_action :set_common_area, only: [:show]

      def index
        return render body: nil, status: :not_found if @condo.nil?

        common_areas = @condo.common_areas.order :name

        render status: :ok, json: { common_areas: common_areas.as_json(only: %i[id name description]) }
      end

      def show
        return render body: nil, status: :not_found if @common_area.nil?

        render status: :ok, json: @common_area.as_json(only: %i[name description max_occupancy rules])
                                              .merge(condo_id: @common_area.condo_id)
      end

      private

      def set_condo
        @condo = Condo.find_by id: params[:condo_id]
      end

      def set_common_area
        @common_area = CommonArea.find_by id: params[:id]
      end
    end
  end
end

app/controllers/common_areas_controller.rb
class CommonAreasController < ApplicationController
  before_action :authenticate_manager!, only: %i[new edit create update]
  before_action :set_condo, only: %i[new create]
  before_action :set_common_area, only: %i[show edit update]
  before_action :set_condo_for_details, only: %i[show edit update]
  before_action -> { authorize_condo_manager(@condo) }, only: %i[new create edit update]
  before_action -> { authorize_user(@condo) }, only: [:show]
  before_action :set_breadcrumbs_for_register, only: %i[new create]
  before_action :set_breadcrumbs_for_details, only: %i[show edit update]

  def show
    @reservations = @common_area.reservations
  end

  def new
    @common_area = CommonArea.new
  end

  def edit
    add_breadcrumb I18n.t('breadcrumb.edit')
  end

  def create
    @common_area = @condo.common_areas.create(common_area_params)
    return redirect_to @common_area, notice: I18n.t('notices.common_area.created') if @common_area.save

    flash.now[:alert] = I18n.t('alerts.common_area.not_created')
    render :new, status: :unprocessable_entity
  end

  def update
    add_breadcrumb I18n.t('breadcrumb.edit')

    unless @common_area.update(common_area_params)
      flash.now[:alert] = I18n.t('alerts.common_area.not_updated')
      return render :edit, status: :unprocessable_entity
    end

    redirect_to @common_area, notice: I18n.t('notices.common_area.updated')
  end

  private

  def common_area_params
    params.require(:common_area).permit(:name, :description, :max_occupancy, :rules)
  end

  def set_condo_for_details
    @condo = @common_area.condo
  end

  def set_condo
    @condo = Condo.find(params[:condo_id])
  end

  def set_common_area
    @common_area = CommonArea.find(params[:id])
  end

  def set_breadcrumbs_for_register
    add_breadcrumb @condo.name, condo_path(@condo)
    add_breadcrumb I18n.t('breadcrumb.common_area.new')
  end

  def set_breadcrumbs_for_details
    add_breadcrumb @common_area.condo.name, condo_path(@common_area.condo)
    add_breadcrumb @common_area.name, common_area_path(@common_area)
  end
end

app/views/common_areas/_reservation_calendar.html.erb
<div class='bg-white rounded-5 py-4 px-5 shadow text-center mt-4 mb-3'>
  <h2 class="mb-3 fs-3 mt-4"><%= manager_signed_in? ? 'Calendário de Reservas' : 'Faça Sua Reserva' %></h2>

  <%= month_calendar(events: @common_area.reservations.confirmed) do |date, reservations| %>
    <strong><%= date.day %></strong>
    
    <% if reservations.any? %>
      <% reservations.each do |reservation| %>
        <% if reservation.date == date %>
          <% if reservation.resident == current_resident || manager_signed_in? %>
            <div class="card text-center">
              <div class="card-body">
                <p class="card-text">Reservado por <%= reservation.resident.full_name %></p>
                <% if reservation.date > Time.zone.today %>
                  <%= button_to 'Cancelar', canceled_common_area_reservation_path(@common_area, reservation), data: { turbo_confirm: "Você tem certeza que deseja cancelar a reserva do dia #{I18n.l(date)}?" }, class: 'btn btn-warning btn-sm rounded-pill shadow-sm' unless manager_signed_in? %>
                <% end %>
              </div>
            </div>
          <% else %>
            <div class="card text-center">
              <div class="card-body">
                <p class="card-text">Reservado</p>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% else %>
      <% if date >= Time.zone.today %>
        <%= button_to 'Reservar', common_area_reservations_path(@common_area, date: date), data: { turbo_confirm: "Você tem certeza que deseja reservar o dia #{I18n.l(date)}?" }, class: 'btn btn-dark btn-sm rounded-pill mt-2 mb-4 shadow-sm' unless manager_signed_in? %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/common_areas/edit.html.erb
<div class='bg-white rounded-5 py-4 px-5 shadow'>
  <h1>Editar área comum</h1>

  <%= form_with model: @common_area do |f| %>
    <div class="form-row row p-2">
      <div class="form-group col-md-6 pe-3 mb-2">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control #{'is-invalid' if @common_area.errors[:name].any?}" %>
        <%= render("shared/errors", model: @common_area, attribute: :name) if @common_area.errors[:name].any? %>
      </div>

      <div class="form-group col-md-6 pe-3 mb-2">
        <%= f.label :max_occupancy%>
        <%= f.number_field :max_occupancy, class: "form-control #{'is-invalid' if @common_area.errors[:max_occupancy].any?}" %>
        <%= render("shared/errors", model: @common_area, attribute: :max_occupancy) if @common_area.errors[:max_occupancy].any? %>
      </div>

      <div class="form-group col-md-6 pe-3 mb-2">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control #{'is-invalid' if @common_area.errors[:description].any?}" %>
        <%= render("shared/errors", model: @common_area, attribute: :description) if @common_area.errors[:description].any? %>
      </div>

      <div class="form-group col-md-6 pe-3 mb-2">
        <%= f.label :rules %>
        <%= f.text_area :rules, class: 'form-control' %>
      </div>
    </div>

    <div class="d-flex justify-content-center">
      <%= f.submit 'Salvar', class: 'btn btn-dark rounded-pill px-4 mt-3' %>
    </div>
  <% end %>
</div>

app/views/common_areas/new.html.erb
<div class='bg-white rounded-5 py-3 px-5 shadow'>
  <h1>Cadastrar nova área comum</h1>

  <%= form_with model: [@condo, @common_area] do |f| %>
    <div class="form-row row p-2">
      <div class="form-group col-md-6 pe-3 mb-2">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control #{'is-invalid' if @common_area.errors[:name].any?}" %>
        <%= render("shared/errors", model: @common_area, attribute: :name) if @common_area.errors[:name].any? %>
      </div>

      <div class="form-group col-md-6 pe-3 mb-2">
        <%= f.label :max_occupancy%>
        <%= f.number_field :max_occupancy, class: "form-control #{'is-invalid' if @common_area.errors[:max_occupancy].any?}" %>
        <%= render("shared/errors", model: @common_area, attribute: :max_occupancy) if @common_area.errors[:max_occupancy].any? %>
      </div>

      <div class="form-group col-md-6 pe-3 mb-2">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control #{'is-invalid' if @common_area.errors[:description].any?}" %>
        <%= render("shared/errors", model: @common_area, attribute: :description) if @common_area.errors[:description].any? %>
      </div>

      <div class="form-group col-md-6 pe-3 mb-2">
        <%= f.label :rules %>
        <%= f.text_area :rules, class: 'form-control' %>
      </div>
    </div>

    <div class="d-flex justify-content-center">
      <%= f.submit 'Salvar', class: 'btn btn-dark rounded-pill px-4 mt-3' %>
    </div>
  <% end %>
</div>

app/views/common_areas/show.html.erb
<div class='bg-white rounded-5 py-4 px-5 shadow text-center'>
  <h1 class="my-4"><%= @common_area.name %></h1>

  <p><%= @common_area.description %></p>
  <p><strong>Capacidade Máxima:</strong> <%= @common_area.max_occupancy %> pessoas</p>
  
  <% if @common_area.rules.present? %>
    <strong>Regras de Uso</strong>
    <p><%= @common_area.rules %></p>
  <% end %>

  <p><strong>Taxa da reserva:</strong> <%= @common_area.formatted_fee %></p>

  <%= link_to 'Editar', edit_common_area_path(@common_area), class: 'btn btn-dark rounded-pill px-4' if manager_signed_in? %>
</div>

<%= render 'common_areas/reservation_calendar' %> 