config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/signup_choice', to: 'home#signup'

  devise_for :managers
  devise_for :residents, controllers: {
    passwords: 'residents/passwords'
  }

  resources :managers, only: [:new, :create] do
    get 'edit_photo', on: :member
    patch 'update_photo', on: :member
  end

  resources :residents, only: [:new, :create, :show, :update] do
    resources :visitors, only: [:new, :create, :index]
    resources :tenants, only: [:new, :create], on: :collection
    resources :owners, only: [:new, :create, :destroy], on: :collection
    get 'find_towers', on: :collection
    get 'confirm', on: :member
    get 'edit_photo', on: :member
    patch 'update_photo', on: :member
  end

  resources :visitors do
    post 'confirm_entry', on: :member
  end

  resource :units do
    get 'find_units', on: :collection
  end

  resources :common_areas, only: [:show, :edit, :update] do
    resources :reservations, only: [:create, :update] do
      post 'canceled', on: :member
    end
  end

  resources :unit_types, only: [:show, :edit, :update]
  resources :announcements, only: [:show, :edit, :update, :destroy]

  resources :bills, only: [:index, :show] do
    resources :receipts, only: [:new, :create]
  end

  resources :condos, only: [:new, :create, :show, :edit, :update] do
    get 'residents', on: :member
    resources :common_areas, only: [:new, :create]
    resources :unit_types, only: [:new, :create]
    resources :visitor_entries, only: [:index, :new, :create]
    resources :superintendents, only: [:show, :new, :create, :destroy]
    resources :announcements, only: [:index, :new, :create]

    resources :visitors do
      get 'find', on: :collection
      get 'all', on: :collection
    end
    resources :fines, only: [:new, :create]

    resources :towers, only: [:new, :create] do
      member do
        get :edit_floor_units
        patch :update_floor_units
      end
    end

    member do
      get 'add_manager'
      post 'associate_manager'
    end
  end

  resources :towers, only: [:show] do
    resources :floors, only: [:show] do
      resources :units, only: [:show]
    end
  end

  namespace :api do
    namespace :v1 do
      get 'check_owner', to: 'residents#check_owner'
      get 'get_tenant_residence', to: 'residents#tenant_residence'
      get 'get_owner_properties', to: 'residents#owner_properties'
      resources :common_areas, only: [:show]
      resources :units, only: [:show]
      resources :condos, only: [:index, :show] do
        resources :unit_types, only: [:index]
        resources :common_areas, only: [:index]
        resources :units, only: [:index]
      end
    end
  end

  direct :rails_blob do |blob, options|
    route_for(:rails_service_blob, blob.signed_id, blob.filename, options)
  end

  direct :rails_blob_variant do |variant, options|
    route_for(:rails_service_blob_variant, variant.blob.signed_id,
              variant.variation.key, variant.blob.filename, options)
  end

  direct :rails_blob_preview do |preview, options|
    route_for(:rails_service_blob_preview, preview.blob.signed_id,
              preview.variation.key, preview.blob.filename, options)
  end

  direct :rails_representation do |representation, options|
    if representation.blob.previewable?
      route_for(:rails_service_blob_preview, representation.blob.signed_id,
                representation.variation.key, representation.blob.filename, options)
    else
      route_for(:rails_service_blob_variant, representation.blob.signed_id,
                representation.variation.key, representation.blob.filename, options)
    end
  end
end

app/models/bill.rb
class Bill
  attr_reader :unit_id, :id, :condo_id, :issue_date, :due_date,
              :total_value_cents, :status, :values, :denied, :bill_details

  def initialize(params = {})
    @unit_id = params.fetch('unit_id', nil)
    @id = params.fetch('id', nil)
    @condo_id = params.fetch('condo_id', nil)
    @issue_date = params.fetch('issue_date', nil)
    @due_date = params.fetch('due_date', nil)
    @total_value_cents = params.fetch('total_value_cents', nil)
    @status = params.fetch('status', nil)
    @values = params.fetch('values', [])
    @denied = params.fetch('denied', nil)
    @bill_details = params.fetch('bill_details', [])
  end

  def self.request_open_bills(unit_id)
    response = Faraday.get("http://localhost:4000/api/v1/units/#{unit_id}/bills")

    return [] unless response.success?

    bills_data = JSON.parse(response.body)['bills']
    bills_array = bills_data.map { |bill_data| new(bill_data) }
    bills_array.sort_by { |bill| bill.due_date.to_time.to_i }.reverse
  end

  def self.safe_request_open_bills(unit_id)
    BillService.request_open_bills(unit_id)
  end

  def self.request_bill_details(bill_id)
    response = Faraday.get("http://localhost:4000/api/v1/bills/#{bill_id}")
    return nil unless response.success?

    bill_data = JSON.parse(response.body)
    new(bill_data)
  end

  def total_value_formatted
    "R$ #{format('%.2f', total_value_cents / 100.0).gsub('.', ',')}"
  end

  def rent_fee_value_formatted
    "R$ #{format('%.2f', values['rent_fee_cents'] / 100.0).gsub('.', ',')}"
  end

  def self.format_value(value)
    "R$ #{format('%.2f', value / 100.0).gsub('.', ',')}"
  end

  def due_date_formatted
    format_date(@due_date)
  end

  def issue_date_formatted
    format_date(@issue_date)
  end

  def self.render_message(response)
    response.success? ? { notice: I18n.t('notices.receipt.sended') } : { alert: I18n.t('alerts.receipt.not_sended') }
  end

  def self.send_post_request(resident, id)
    image_attached_blob = resident.receipt.attachment.blob
    url = Rails.application.routes.url_helpers.rails_blob_url(image_attached_blob, host: 'localhost:3000')
    Faraday.post('http://localhost:4000/api/v1/receipts',
                 { receipt: url, bill_id: id }.to_json, 'Content-Type' => 'application/json')
  end

  private

  def format_date(date)
    Date.parse(date).strftime('%d/%m/%Y')
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  rescue_from Faraday::ConnectionFailed, with: :connection_refused
  before_action :authenticate_resident!, only: %i[index show]
  before_action :unit_for_current_resident, only: %i[index show]
  before_action :request_open_bills_list, only: :index
  before_action :request_bill_details, only: :show
  before_action :autorize_resident, only: :show
  before_action :set_breadcrumbs_for_action, only: %i[index show]

  def index; end

  def show; end

  private

  def unit_for_current_resident
    @unit = current_resident.residence
  end

  def request_open_bills_list
    @bills = Bill.request_open_bills(@unit.id)
  end

  def request_bill_details
    @bill_id = params[:id]
    @bill = Bill.request_bill_details(params[:id])

    redirect_to bills_path, alert: t('alerts.bill.not_found') unless @bill
  end

  def connection_refused
    redirect_to root_path, alert: t('alerts.lost_connection')
  end

  def set_breadcrumbs_for_action
    add_breadcrumb I18n.t("breadcrumb.bill.#{action_name}")
  end

  def autorize_resident
    redirect_to root_path, alert: t('alerts.receipt.not_autorized') unless @bill.unit_id == @unit.id
  end
end

app/views/bills/index.html.erb
  <div class='bg-white rounded-5 py-4 px-5 shadow'>
    <section>
      <h1>Minhas Faturas</h1>
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Valor</th>
            <th scope="col">Lançamento</th>
            <th scope="col">Vencimento</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody class="bills-list">
          <% if @bills.present? && @bills.any? %>
            <% @bills.each do |bill| %>
              <tr class="bill">          
                <td><%= bill.total_value_formatted %></td>
                <td><%= bill.issue_date_formatted %></td>
                <td><%= bill.due_date_formatted %></td>
                <td>
                  <%= link_to bill_path(bill.id), class: "ms-auto btn btn-dark d-inline-flex align-items-center rounded-pill" do %>
                    <p class="m-0 fs-sm">Detalhes</p> <i class="bi bi-search ms-1"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% else %>
            <p>Não há faturas em aberto</p>
          <% end %>
        </tbody>
      </table>
    </section>
  </div>

app/views/bills/new.html.erb
<div class='bg-white rounded-5 py-3 px-5 shadow'>
  <h1>Comprovante de Pagamento</h1>

  <%= form_with url: bill_bills_path(@bill_id), local: true, multipart: true do |f| %>
    <div class="form-floating mb-3 w-75">
      <%= f.file_field :image, class: 'form-control' %>
      <%= f.label :image, "Comprovante" %>
    </div>

    <%= f.submit 'Enviar', class: 'btn btn-dark rounded-pill px-4 mt-1' %>
  <% end %>
</div>

app/views/bills/show.html.erb
<section class="bg-white rounded-5 py-4 px-5 shadow">
  <h1 class="mb-3">Minha Fatura</h1>

  <div class="mt-4 text-muted small">
    <p><strong>Unidade:</strong> <%= @unit.short_identifier %></p>
    <p><strong>Condomínio:</strong> <%= @unit.condo.name %></p>
  </div>

  <div class="d-flex justify-content-center">
    <div class="card mt-4 border border-primary shadow-lg w-25">
      <div class="card-body d-flex flex-column align-items-center">
        <p class="fs-3"><strong>Valor:</strong> <%= @bill.total_value_formatted %></p>
        <strong>Vencimento:</strong> <%= @bill.due_date_formatted %>
        <strong>Lançamento:</strong> <%= @bill.issue_date_formatted %>
        <div>
          <% case @bill.status %>
          <% when 'pending' %>
            <% if @bill.denied %>
              <span class="badge rounded-pill text-bg-danger">Negada</span>
            <% else %>
              <span class="badge rounded-pill text-bg-warning">Não paga</span>
            <% end %>
          <% when 'awaiting' %>
            <span class="badge rounded-pill text-bg-info">Em análise</span>
          <% when 'paid' %>
            <span class="badge rounded-pill text-bg-success">Paga</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center mt-4">
    <% if @bill.status == 'pending' %>
      <%= link_to new_bill_receipt_path(@bill_id, unit_id: @bill.unit_id), class:"btn btn-dark rounded-pill d-flex align-items-baseline pb-2 mb-2 shadow-sm" do %>
        <i class="bi bi-card-text me-1 fs-6"></i> <p class="m-0 fs-sm">Enviar Comprovante</p> 
      <% end %>
    <% end %>
  </div>

  <h2 class="mb-3">Detalhamento</h2>

  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">Descrição</th>
        <th scope="col">Valor</th>
      </tr>
    </thead>
    <tbody>
      <% @bill.bill_details.each do |detail| %>
        <tr>
          <td><%= detail['description'] %></td>
          <td><%= Bill.format_value detail['value_cents'] %></td>
        </tr>
      <% end %>
      <% if @bill.rent_fee_value_formatted %>
      <tr>
        <td> Aluguel </td>
        <td> <%= @bill.rent_fee_value_formatted %>
      </tr>
      <% end%>
      <tr>
        <td><strong>Total</strong></td>
        <td><strong><%= @bill.total_value_formatted %></strong></td>
      </tr>
    </tbody>
  </table>
</section>