config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  get '/signup_choice', to: 'home#signup'

  devise_for :managers
  devise_for :residents, controllers: {
    passwords: 'residents/passwords'
  }

  resources :managers, only: [:new, :create] do
    get 'edit_photo', on: :member
    patch 'update_photo', on: :member
  end

  resources :residents, only: [:new, :create, :show, :update] do
    resources :visitors, only: [:new, :create, :index]
    resources :tenants, only: [:new, :create], on: :collection
    resources :owners, only: [:new, :create, :destroy], on: :collection
    get 'find_towers', on: :collection
    get 'confirm', on: :member
    get 'edit_photo', on: :member
    patch 'update_photo', on: :member
  end

  resources :visitors do
    post 'confirm_entry', on: :member
  end

  resource :units do
    get 'find_units', on: :collection
  end

  resources :common_areas, only: [:show, :edit, :update] do
    resources :reservations, only: [:create, :update] do
      post 'canceled', on: :member
    end
  end

  resources :unit_types, only: [:show, :edit, :update]
  resources :announcements, only: [:show, :edit, :update, :destroy]

  resources :bills, only: [:index, :show] do
    resources :receipts, only: [:new, :create]
  end

  resources :condos, only: [:new, :create, :show, :edit, :update] do
    get 'residents', on: :member
    resources :common_areas, only: [:new, :create]
    resources :unit_types, only: [:new, :create]
    resources :visitor_entries, only: [:index, :new, :create]
    resources :superintendents, only: [:show, :new, :create, :destroy]
    resources :announcements, only: [:index, :new, :create]

    resources :visitors do
      get 'find', on: :collection
      get 'all', on: :collection
    end
    resources :fines, only: [:new, :create]

    resources :towers, only: [:new, :create] do
      member do
        get :edit_floor_units
        patch :update_floor_units
      end
    end

    member do
      get 'add_manager'
      post 'associate_manager'
    end
  end

  resources :towers, only: [:show] do
    resources :floors, only: [:show] do
      resources :units, only: [:show]
    end
  end

  namespace :api do
    namespace :v1 do
      get 'check_owner', to: 'residents#check_owner'
      get 'get_tenant_residence', to: 'residents#tenant_residence'
      get 'get_owner_properties', to: 'residents#owner_properties'
      resources :common_areas, only: [:show]
      resources :units, only: [:show]
      resources :condos, only: [:index, :show] do
        resources :unit_types, only: [:index]
        resources :common_areas, only: [:index]
        resources :units, only: [:index]
      end
    end
  end

  direct :rails_blob do |blob, options|
    route_for(:rails_service_blob, blob.signed_id, blob.filename, options)
  end

  direct :rails_blob_variant do |variant, options|
    route_for(:rails_service_blob_variant, variant.blob.signed_id,
              variant.variation.key, variant.blob.filename, options)
  end

  direct :rails_blob_preview do |preview, options|
    route_for(:rails_service_blob_preview, preview.blob.signed_id,
              preview.variation.key, preview.blob.filename, options)
  end

  direct :rails_representation do |representation, options|
    if representation.blob.previewable?
      route_for(:rails_service_blob_preview, representation.blob.signed_id,
                representation.variation.key, representation.blob.filename, options)
    else
      route_for(:rails_service_blob_variant, representation.blob.signed_id,
                representation.variation.key, representation.blob.filename, options)
    end
  end
end

app/models/condo.rb
class Condo < ApplicationRecord
  belongs_to :address
  has_many :towers, dependent: :destroy
  has_many :common_areas, dependent: :destroy
  has_many :unit_types, dependent: :destroy
  has_many :condo_managers, dependent: :destroy
  has_many :managers, through: :condo_managers
  has_many :announcements, dependent: :destroy
  has_many :visitors, dependent: :destroy
  has_many :visitor_entries, dependent: :destroy
  has_many :floors, through: :towers
  has_many :units, through: :floors
  has_many :owners, through: :units
  has_many :tenants, through: :units
  has_many :superintendents, dependent: :destroy

  delegate :city, to: :address
  delegate :state, to: :address

  validates :name, presence: true
  validates :registration_number, uniqueness: true
  validate :validate_cnpj

  accepts_nested_attributes_for :address

  def superintendent
    superintendents.not_closed[0]
  end

  def residents
    (tenants + owners).uniq
  end

  def filtered_residence_registration_pendings
    (tenants.residence_registration_pending + owners.residence_registration_pending).uniq
  end

  def filtered_property_registration_pendings
    (tenants.property_registration_pending + owners.property_registration_pending).uniq
  end

  def full_address
    <<~HEREDOC.strip
      #{address.public_place}, #{address.number}, #{address.neighborhood} - \
      #{address.city}/#{address.state} - CEP: #{address.zip}
    HEREDOC
  end

  def set_unit_types_fractions
    total_area = calculate_total_area
    return if total_area.zero?

    unit_types.each do |unit_type|
      fraction = (unit_type.metreage / total_area * 100).round(5)
      unit_type.update!(fraction:)
    end
  end

  def units_json
    ordered_units.map do |unit|
      {
        id: unit.id,
        floor: unit.floor.identifier,
        number: unit.short_identifier,
        tower_name: unit.tower.name
      }
    end
  end

  def expected_visitors(date)
    visitors.where(visit_date: date)
  end

  def search_visitors_by_resident_name(resident_name)
    visitors.joins(:resident).where('residents.full_name LIKE ?', "%#{resident_name}%")
  end

  def search_visitors_by_params(key, value)
    visitors.where("#{key} LIKE ?", "%#{value}%")
  end

  def three_most_recent_announcements
    announcements.order(updated_at: :desc).limit(3)
  end

  def more_than_3_announcements
    announcements.count > 3
  end

  private

  def ordered_units
    towers.flat_map { |tower| tower.floors.flat_map(&:units) }
  end

  def calculate_total_area
    total_area = 0
    unit_types.each do |unit_type|
      total_area += unit_type.metreage * unit_type.units.count
    end

    total_area
  end

  def validate_cnpj
    if CNPJ.valid? registration_number
      cnpj_regex = %r{\A\d{2}[\.]\d{3}[\.]\d{3}[\/]\d{4}-\d{2}\z}
      unless registration_number.match cnpj_regex
        errors.add(:registration_number, 'deve estar no seguinte formato: XX.XXX.XXX/XXXX-XX')
      end
    else
      errors.add(:registration_number, 'inválido')
    end
  end
end

app/controllers/api/v1/condos_controller.rb
module Api
  module V1
    class CondosController < Api::V1::ApiController
      def index
        render status: :ok, json: Condo.all.as_json(only: %i[id name],
                                                    methods: %i[city state])
      end

      def show
        condo = Condo.find_by id: params[:id]
        return render body: nil, status: :not_found if condo.nil?

        render status: :ok,
               json: condo.as_json(only: %i[name registration_number],
                                   include: { address: { only: %i[public_place
                                                                  number
                                                                  neighborhood
                                                                  city
                                                                  state
                                                                  zip] } })
      end
    end
  end
end

app/controllers/condos_controller.rb
class CondosController < ApplicationController
  before_action :authenticate_manager!, only: %i[new create edit update residents]
  before_action :set_condo, only: %i[show edit update add_manager associate_manager residents]
  before_action :set_breadcrumbs_for_details, only: %i[show edit update add_manager associate_manager]
  before_action :authorize_super_manager, only: %i[new create add_manager associate_manager]
  before_action -> { authorize_condo_manager(@condo) }, only: %i[edit update residents]
  before_action -> { authorize_user(@condo) }, only: [:show]
  before_action :announcements_for_dashboard, only: :show

  def show
    @residents = @condo.residents
    @towers = @condo.towers.order :name
    @common_areas = @condo.common_areas.order :name
    @unit_types = @condo.unit_types.order :description
    @todays_visitors = visitors_list(@condo)
    request_bills
  end

  def new
    add_breadcrumb I18n.t('breadcrumb.condo.new')
    @condo = Condo.new
  end

  def edit
    add_breadcrumb I18n.t('breadcrumb.edit')
  end

  def create
    add_breadcrumb I18n.t('breadcrumb.condo.new')
    @condo = Condo.new(condo_params)

    unless @condo.save
      flash.now[:alert] = t('alerts.condo.not_created')
      return render :new, status: :unprocessable_entity
    end

    redirect_to @condo, notice: t('notices.condo.created')
  end

  def update
    add_breadcrumb I18n.t('breadcrumb.edit')

    unless @condo.update(condo_params)
      flash.now[:alert] = t('alerts.condo.not_updated')
      return render :edit, status: :unprocessable_entity
    end

    redirect_to @condo, notice: t('notices.condo.updated')
  end

  def add_manager
    add_breadcrumb I18n.t('breadcrumb.condo.new_manager')
    @managers = Manager.where(is_super: false).where.not(id: @condo.managers.pluck(:id)).order(:full_name)
  end

  def associate_manager
    @manager = Manager.find(params[:manager_id])
    if @condo.managers.exclude?(@manager) && (@condo.managers << @manager)
      return redirect_to @condo,
                         notice: I18n.t('notices.condo.manager_associated')
    end

    redirect_to @condo, alert: I18n.t('alerts.condo.manager_not_associated')
  end

  def residents
    return render status: :ok, json: @condo.residents.as_json(only: %i[id full_name]) if @condo

    render status: :not_found, json: []
  end

  private

  def set_breadcrumbs_for_details
    add_breadcrumb @condo.name.to_s, condo_path(@condo)
  end

  def condo_params
    params.require(:condo).permit(:name, :registration_number,
                                  address_attributes: %i[public_place number neighborhood city state zip])
  end

  def set_condo
    @condo = Condo.find_by(id: params[:id])
  end

  def visitors_list(condo)
    resident_signed_in? ? current_resident.todays_visitors : condo.expected_visitors(Time.zone.today)
  end

  def request_bills
    return unless resident_signed_in? && current_resident.residence.present?

    result = Bill.safe_request_open_bills(current_resident.residence.id)
    @bills = result[:bills]
    @bills_error = result[:error]
  end

  def announcements_for_dashboard
    @announcements = @condo.three_most_recent_announcements
    @more_than_3_announcements = @condo.more_than_3_announcements
  end
end

app/views/condos/_form.html.erb
<%= form_with(model: @condo) do |f| %>
  <div class="form-row d-flex p-2">
    <div class="form-group col-md-6 pe-3">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control #{'is-invalid' if @condo.errors[:name].any?}" %>
      <%= render("shared/errors", model: @condo, attribute: :name) if @condo.errors[:name].any? %>
    </div>
    
    <div class="form-group col-md-6" data-controller="mask">
      <%= f.label :registration_number %>
      <%= f.text_field :registration_number, class:"form-control #{'is-invalid' if @condo.errors[:registration_number].any?}", 
          placeholder: "00.111.222/3333-44", maxlength: "18", :'data-action' => 'keyup->mask#RegistrationNumberPressed' %>
      <%= render("shared/errors", model: @condo, attribute: :registration_number) if @condo.errors[:registration_number].any? %>
    </div>
  </div>

  <div>
    <%= f.fields_for :address, @condo.address || Address.new do |address_f| %>
      <div class="form-row d-flex p-2">
        <div class="form-group col-md-6 pe-3">
          <%= address_f.label :public_place %>
          <%= address_f.text_field :public_place, class:"form-control #{'is-invalid' if address_f.object.errors[:public_place].any?}" %>
          <%= render("shared/errors", model: address_f.object, attribute: :public_place) if address_f.object.errors[:public_place].any? %>
        </div>

        <div class="form-group col-md-2 pe-3">
          <%= address_f.label :number %>
          <%= address_f.text_field :number, class:"form-control #{'is-invalid' if address_f.object.errors[:number].any?}" %>
          <%= render("shared/errors", model: address_f.object, attribute: :number) if address_f.object.errors[:number].any? %>
        </div>

        <div class="form-group col-md-4 pe-3">
          <%= address_f.label :neighborhood %>
          <%= address_f.text_field :neighborhood, class:"form-control #{'is-invalid' if address_f.object.errors[:neighborhood].any?}" %>
          <%= render("shared/errors", model: address_f.object, attribute: :neighborhood) if address_f.object.errors[:neighborhood].any? %>
        </div>
      </div>

      <div class="form-row d-flex p-2">
        <div class="form-group col-md-6 pe-3">
          <%= address_f.label :city %>
          <%= address_f.text_field :city, class:"form-control #{'is-invalid' if address_f.object.errors[:city].any?}" %>
          <%= render("shared/errors", model: address_f.object, attribute: :city) if address_f.object.errors[:city].any? %>
        </div>

        <div class="form-group col-md-2 pe-3">
          <%= address_f.label :state %>
          <%= address_f.select :state, options_for_select(Address::STATES), {}, 
          class:"form-control form-select" %>
        </div>

        <div class="form-group col-md-4 pe-3" data-controller="mask">
          <%= address_f.label :zip %>
          <%= address_f.text_field :zip, class:"form-control #{'is-invalid' if address_f.object.errors[:zip].any?}", placeholder: "12345-678",
          maxlength: "9", :'data-action' => 'keyup->mask#zipPressed' %>
          <%= render("shared/errors", model: address_f.object, attribute: :zip) if address_f.object.errors[:zip].any? %>
        </div>
      </div>
    <% end %>

    <div class="d-flex justify-content-center">
      <%= f.submit 'Salvar', class:"btn btn-dark rounded-pill px-4 mt-3" %>
    </div>
  </div>
<% end %>

app/views/condos/add_manager.html.erb
<div class='bg-white rounded-5 py-3 px-5 shadow'>
  <h1>Adicionar Administrador</h1>

  <div id ="associate_manager_condo">
    <%= form_with url: associate_manager_condo_path(@condo), method: :post do %>
      <div class="mb-3">
        <%= label_tag :manager_id, Condo.human_attribute_name(:manager_id), class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10"><%= select_tag :manager_id, options_from_collection_for_select(@managers, :id, :full_name), class: "form-control" %></div>
      </div>
      <%= submit_tag 'Adicionar', class: 'btn btn-dark rounded-pill px-4 mt-1' %>
    <% end %>
  </div>
</div>

app/views/condos/edit.html.erb
<section class="bg-white rounded-5 py-4 px-5 shadow">
  <h1>Editar Condomínio</h1>
  <%= render 'form' %>
</section>

app/views/condos/new.html.erb
<section class="bg-white rounded-5 py-4 px-5 shadow">
  <h1>Cadastre um novo Condomínio</h1>
  <%= render 'form' %>
</section>

app/views/condos/show.html.erb
<div class="text-center row justify-content-center">
  <div class="p-0 w-fit">
    <h1 class="text-center"><%= @condo.name %></h1>
    <p class="mb-1 text-secondary fs-sm" ><%= @condo.full_address %></p>
    <p class="mb-1 text-secondary fs-sm">CNPJ: <%= @condo.registration_number %></p>
    <p class="mb-1 text-secondary fs-sm">Síndico: 
      <% if @condo.superintendent%>
        <%= link_to condo_superintendent_path(@condo, @condo.superintendent) do %> 
          <%= @condo.superintendent.condo_presentation%>
        <% end %>
      <% else %>
        Não há um síndico ativo
      <% end %>  
    </p>
  </div>
</div>

<hr>

<div class="row row-cols-3">
  <div class="col">
    <%= render 'condos/dashboard/announcement_board' %>

    <div class="card rounded-5 mt-2 shadow-sm">
      <strong class="card-header text-center rounded-top-5 bg-light-yellow">Agenda de Reuniões</strong>
      <div class="card-body">
        <div class="alert alert-warning text-center">Em breve</div>
      </div>
    </div>

    <%= link_to '#', class: 'btn btn-warning border-0 d-flex align-items-center justify-content-center rounded-pill py-2 mt-2 fw-bolder shadow-sm bg-light-yellow' do %>
      <p class="m-0">Ver registro de reclamações e ocorrências</p>
      <span class="badge text-bg-light mt-1 ms-1 rounded-pill">Em breve</span>
    <% end %>
  </div>

  <div class="col">
    <% if manager_signed_in? %>
      <%= link_to new_condo_visitor_entry_path(@condo), class:"btn py-2 btn-warning border-0 rounded-pill d-flex justify-content-center align-items-center mb-2 shadow-sm bg-light-yellow w-100" do %>
        <strong>Registrar entrada de visitante</strong>
        <i class="bi bi-pencil-square pb-1 ms-1"></i>
      <% end %>
      <%= link_to condo_visitor_entries_path(@condo), class:"btn btn-warning border-0 py-2 rounded-pill d-flex justify-content-center align-items-center mb-2 shadow-sm bg-light-yellow w-100" do %>
        <strong>Lista de Entradas</strong>
        <i class="bi bi-search ms-1"></i>
      <% end %>
      <%= link_to find_condo_visitors_path(@condo), class:"btn py-2 btn-warning border-0 rounded-pill d-flex justify-content-center align-items-center mb-2 shadow-sm bg-light-yellow w-100" do %>
        <strong>Agenda de visitantes/funcionários</strong>
        <i class="bi bi-people-fill ms-1"></i>
      <% end %>
    <% end %>
    <% if resident_signed_in? && current_resident.residence&.condo == @condo %>
      <%= render 'condos/dashboard/todays_visitors' %> 
    <% end %>
  </div>

  <div class="col">
    <% if manager_signed_in? %>
      <%= link_to edit_condo_path, class:"btn btn-warning border-0 py-2 rounded-pill d-flex justify-content-center align-items-center mb-2 shadow-sm bg-light-yellow w-100" do %>
        <strong>Editar Condomínio</strong>
        <i class="bi bi-pencil-square pb-1 ms-1"></i>
      <% end %>
        <div class="accordion">
          <% if current_manager.is_super %>
            <%= link_to add_manager_condo_path(@condo), class:"btn btn-warning border-0 py-2 rounded-pill d-flex justify-content-center align-items-center mb-2 shadow-sm bg-light-yellow w-100" do %>
              <strong>Adicionar Administrador</strong>
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-fill-add pb-0 ms-1" viewBox="0 0 16 16">
                <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0m-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                <path d="M2 13c0 1 1 1 1 1h5.256A4.5 4.5 0 0 1 8 12.5a4.5 4.5 0 0 1 1.544-3.393Q8.844 9.002 8 9c-5 0-6 3-6 4"/>
              </svg>
            <% end %>
          <% end %>
        </div>
    <% end %>
    
    <div class="accordion">
      <% if manager_signed_in? %>
        <%= render 'condos/dashboard/tower_list' %>
        <%= render 'condos/dashboard/unit_type_list' %>
        <%= render 'condos/dashboard/residents_list' %>
      <% end %>

      <%= render 'condos/dashboard/common_area_list' %>

      <% if resident_signed_in? && current_resident&.superintendent %>
        <%= link_to new_condo_fine_path(@condo), class:"btn py-2 rounded-pill d-flex justify-content-center align-items-center mb-2 shadow-sm mt-2", style: "width: 100%; background-color: #FDE879;" do %>
          <strong>Lançar Multa</strong>
          <svg xmlns="http://www.w3.org/2000/svg" width="19" height="18" fill="currentColor" class="bi bi-cash-coin pb-0 ms-1" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8m5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0"/>
            <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195z"/>
            <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083q.088-.517.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1z"/>
            <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 6 6 0 0 1 3.13-1.567"/>
          </svg>      
        <% end %>
      <% end %>

    </div>

    <div class="accordion mt-2">
      <% if resident_signed_in? %>
        <%= render 'condos/dashboard/bills' %>
      <% end %>
    </div>
  </div>
</div>